#! /usr/bin/env ruby

def svn_diff(args, repository)
  colorizer = old = otag = new = ntag = page = param = revision = ''
  details   = sumforce = debug = false
  summary   = '--summarize'

  base   = repository[:base]
  trunk  = repository[:trunk]
  branch = repository[:branch]

  params = {'-o' => 'old', '-n' => 'new', '-s' => 'sub', '-f' => 'file', '-d' => 'folder', '-r' => 'revision', '-c' => 'colorizer'}

  args.each do |item|
    if params.has_key? item
      param = params[item]
      next
    end

    val = item[2..-1]
    if params.has_value? val
      param = val
      next
    end

    case item
      when '--details'
        details = true
      when '--summary'
        sumforce = true
      when '--debug'
        debug = true
      else
        case param
          when 'colorizer'
            colorizer = item
          when 'file'
            page    = item
            details = true
          when 'folder'
            page = item
          when 'old'
            old = item
          when 'new'
            new = item
          when 'revision'
            revision = item
            details  = true
          when 'sub'
            page = item
            if item[-1, 1] != '/'
              details = true
            end
          else
            #do something?
        end
    end

    param = ""
  end

  if revision.empty?
    if old.empty? || old == trunk
      otag = ""
      old  = "#{ trunk }/"
    else
      otag = "#{ old }/"
      old  = "#{ branch }/"
    end

    if new.empty? || new == trunk
      ntag = ""
      new  = "#{ trunk }/"
    else
      ntag = "#{ new }/"
      new  = "#{ branch }/"
    end

    path  = "#{ base }#{ old }#{ otag }#{ page } #{ base }#{ new }#{ ntag }#{ page }"
    hpath = "#{ old }#{ otag }#{ page } #{ new }#{ ntag }#{ page }"
  else
    unless revision.include? ':'
      revision = (revision.to_i - 1).to_s + ':' + revision
    end

    path  = "-r #{ revision } #{ base }"
    hpath = "revision #{ revision }"
  end

  if details == true && sumforce == false
    summary = ''

    if colorizer.empty?
      %w(diffc colordiff).each do |colorer|
        output = `which #{ colorer } 2>&1`
        if output.empty?
          next
        end

        summary = "| #{ colorer }"
        break
      end
    else
      output = `which #{ colorizer } 2>&1`
      unless output.empty?
        summary = "| #{ colorizer }"
      end
    end
  end

  if sumforce
    summary = '--summarize'
  end

  command = "svn diff -x -w #{ path } #{ summary }"

  head = 'SVN diff ' + (summary.empty? ? 'details' : 'summary') + " for #{ hpath }"
  l    = '=' * (head.length + 2)
  s    = ' ' * (head.length + 2)
  puts "\n+#{ l }+\n|#{ s }|\n| #{ head } |\n|#{ s }|\n+#{ l }+"

  if debug
    puts command
  end

  output = `#{ command } 2>&1`
  if summary != '--summarize'
    puts "\n" + output
    exit
  end

  added     = []
  deleted   = []
  modified  = []
  mtype     = %w(M D A)
  pmodified = []
  maxlen    = 0

  output.each_line do |line|
    type = line[0, 1]
    prop = line[1, 1]
    file = line[2..-1].strip.sub(base + old + otag, '')

    case type
      when 'M'
        modified << file
      when 'D'
        deleted << file
      when 'A'
        added << file
      else
        #do something?
    end

    if prop == 'M'
      pmodified << file
    end

    if maxlen < file.length
      maxlen = file.length
    end
  end

  if added.empty? && modified.empty? && deleted.empty?
    puts 'No differences found'
  else
    l = '-' * (maxlen + 1)

    unless modified.empty?
      modified.sort!
      puts "\nModified\n#{ l }\n" + modified.join("\n")
    end

    unless added.empty?
      added.sort!
      header = "Missing from #{ old }#{ otag }"
      puts "\n#{ header }\n#{ l }\n" + added.join("\n")
    end

    unless deleted.empty?
      deleted.sort!
      header = "Missing from #{ new }#{ ntag }"
      puts "\n#{ header }\n#{ l }\n" + deleted.join("\n")
    end

    unless pmodified.empty?
      pmodified.sort!
      header = 'SVN properties changed'
      puts "\n#{ header }\n#{ l }\n" + pmodified.join("\n")
    end
  end
end

def svn_diff_help command = 'svndiff'
  header = "#{ command } help"
  l      = '-' * header.length
  h      = "#{ header }\n#{ l }"
  puts <<-HELP

#{ h }

Compares differences between revisions or branches and the trunk.

param			description
-----			-----------
-c (--colorizer) XXXX	A diff coloring app like diffc, colordiff. If one of these exist, it will choose automatically. If specified, it will use the specified app.
-d (--folder) XXXX	A folder that should be compared (i.e. web/). Never sets --details flag.
-f (--file) XXXX	A file that should be compared (i.e. web/index.php). Sets --details flag automatically.
-o (--old) XXXX		The old branch that should be compared against. (i.e. --old sprint8). If missing, assumes trunk.
-n (--new) XXXX		The new branch that should be compared against. (i.e. --new sprint8-stage). If missing, assumes trunk.
-p (--repository) XXXX  Use the repository defined in the config file.
-r (--revision) XXXX	Compare the differences between revisions rather than branches (i.e. -r 10301 or -r 10200:10301). Sets the --details flag automatically.
-s (--sub) XXXX		A file (or folder) that should be compared (i.e. web/).
			If the param has a trailing forward slash, it is assumed that it is a folder. Otherwise it sets --details flag automatically.

--debug			Prints various debug statements
--details		Get the diff details instead of summary of all the changes.
--summary		Force summary mode.

examples
--------
To get a summary of changes between branches:
#{ command } -o sprint9 -n sprint10
#{ command } --old sprint9 --new sprint10

To get detailed changes for all files between branches:
#{ command } -o sprint9 -n sprint10 --details
#{ command } --old sprint9 --new sprint10 --details

To get a summary of changes between the trunk and a branch:
#{ command } --new sprint9
#{ command } --old trunk --new sprint9

To get detailed changes for a file between branches:
#{ command } --old sprint9 --new sprint10 --file lib/class/MyClass.php
#{ command } --old sprint9 --new sprint10 --sub lib/class/MyClass.php

To get a summary of changes between a sub folder between branches:
#{ command } --old sprint9 --new sprint10 --folder lib/class
#{ command } --old sprint9 --new sprint10 --folder lib/class/
#{ command } --old sprint9 --new sprint10 --sub lib/class/

To get a detailed view of changes between a sub folder between branches:
#{ command } --old sprint9 --new sprint10 --folder lib/class --details
#{ command } --old sprint9 --new sprint10 --folder lib/class/ --details
#{ command } --old sprint9 --new sprint10 --sub lib/class/ --details
#{ command } --old sprint9 --new sprint10 --sub lib/class (notice the lack of trailing forward slash)

To get a detailed view of changes between sequential revisions:
#{ command } -r 10301 (same as #{ command } -r 10300:10301)
#{ command } --revision 10301

To get a detailed view of changes between revisions:
#{ command } -r 10210:10301
#{ command } --revision 10210:10301

To get a summary of difference between revisions:
#{ command } --revision 10301 --summary
  HELP
end


if __FILE__ == $0
  unless ARGV.empty?
    load File.dirname(__FILE__) + '/svntools'

    result     = parse_args ARGV
    args       = result[:args]
    repository = result[:repository]

    svn_diff(args, repository)
    exit
  end

  svn_diff_help
end
